/** Official World Cup 2026 teams — synced with WorldCupOfficialFixtures.cs */
export const WC_TEAMS: ReadonlyArray<{ teamId: string; name: string }> = [
  { teamId: 'mexico', name: 'Mexico' },
  { teamId: 'south-africa', name: 'South Africa' },
  { teamId: 'south-korea', name: 'South Korea' },
  { teamId: 'czechia', name: 'Czechia' },
  { teamId: 'canada', name: 'Canada' },
  { teamId: 'bosnia-herzegovina', name: 'Bosnia and Herzegovina' },
  { teamId: 'qatar', name: 'Qatar' },
  { teamId: 'switzerland', name: 'Switzerland' },
  { teamId: 'brazil', name: 'Brazil' },
  { teamId: 'morocco', name: 'Morocco' },
  { teamId: 'haiti', name: 'Haiti' },
  { teamId: 'scotland', name: 'Scotland' },
  { teamId: 'usa', name: 'United States' },
  { teamId: 'paraguay', name: 'Paraguay' },
  { teamId: 'australia', name: 'Australia' },
  { teamId: 'turkiye', name: 'Türkiye' },
  { teamId: 'germany', name: 'Germany' },
  { teamId: 'curacao', name: 'Curaçao' },
  { teamId: 'ivory-coast', name: 'Ivory Coast' },
  { teamId: 'ecuador', name: 'Ecuador' },
  { teamId: 'netherlands', name: 'Netherlands' },
  { teamId: 'japan', name: 'Japan' },
  { teamId: 'sweden', name: 'Sweden' },
  { teamId: 'tunisia', name: 'Tunisia' },
  { teamId: 'belgium', name: 'Belgium' },
  { teamId: 'egypt', name: 'Egypt' },
  { teamId: 'iran', name: 'Iran' },
  { teamId: 'new-zealand', name: 'New Zealand' },
  { teamId: 'spain', name: 'Spain' },
  { teamId: 'cape-verde', name: 'Cape Verde' },
  { teamId: 'saudi-arabia', name: 'Saudi Arabia' },
  { teamId: 'uruguay', name: 'Uruguay' },
  { teamId: 'france', name: 'France' },
  { teamId: 'senegal', name: 'Senegal' },
  { teamId: 'norway', name: 'Norway' },
  { teamId: 'iraq', name: 'Iraq' },
  { teamId: 'argentina', name: 'Argentina' },
  { teamId: 'algeria', name: 'Algeria' },
  { teamId: 'austria', name: 'Austria' },
  { teamId: 'jordan', name: 'Jordan' },
  { teamId: 'portugal', name: 'Portugal' },
  { teamId: 'colombia', name: 'Colombia' },
  { teamId: 'dr-congo', name: 'DR Congo' },
  { teamId: 'uzbekistan', name: 'Uzbekistan' },
  { teamId: 'england', name: 'England' },
  { teamId: 'croatia', name: 'Croatia' },
  { teamId: 'ghana', name: 'Ghana' },
  { teamId: 'panama', name: 'Panama' },
];

export function getWcTeamById(teamId?: string | null) {
  if (!teamId?.trim()) return null;
  const key = teamId.trim().toLowerCase();
  return WC_TEAMS.find((t) => t.teamId === key) ?? null;
}
